### ISSUE TITLE
插件无法连接服务器但是gm工具可以找不到头绪望得到解答

### ISSUE THREAD

**Issue by chutiangekmm** [Zyy955/Yunzai-GrasscutterCommand#4]
插件无法连接服务器但是gm工具可以找不到头绪望得到解答

![VWY({S0~1OXXV2ZJ})AFDE7](https://github.com/Zyy955/Yunzai-GrasscutterCommand/assets/30683090/ad1f7333-99ab-4d73-a001-1d12222f934e)

![image](https://github.com/Zyy955/Yunzai-GrasscutterCommand/assets/30683090/3eecf418-bd0d-4e8c-a0a5-88dafc5367bb)

![image](https://github.com/Zyy955/Yunzai-GrasscutterCommand/assets/30683090/439eac11-6723-4f08-bc4d-ff1e3932191d)

**Comment by Zyy955** [comment]
啊这，目前我本人已经很久不接触了，插件已经是处于停更状态了...

**Comment by chutiangekmm** [comment]
> 啊这，目前我本人已经很久不接触了，插件已经是处于停更状态了...

好的感谢回复。能问一下您当时还在使用的时候opencommand的版本您还有映像么。
